apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace: travel-control
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  controlPlaneRef:
    name: basic
    namespace: istio-system