apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vm-pool-hpa
  namespace: travel-control
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: pool.kubevirt.io/v1alpha1
    kind: VirtualMachinePool
    name: travel-control-vm-pool
  targetCPUUtilizationPercentage: 50