apiVersion: v1
kind: Service
metadata:
  name: control
  namespace: travel-control
  labels:
    app: control
spec:
  ports:
    - port: 8080
      name: http
  selector:
    kubevirt.io/domain: control
