apiVersion: v1
kind: Service
metadata:
  name: discounts-vm
  namespace: travel-agency
  labels:
    app: discounts-vm
spec:
  ports:
    - port: 8000
      name: http
  selector:
    kubevirt.io/domain: discounts-vm