apiVersion: v1
kind: Service
metadata:
  name: flights-vm
  namespace: travel-agency
  labels:
    app: flights-vm
spec:
  ports:
    - port: 8000
      name: http
  selector:
    kubevirt.io/domain: flights-vm