apiVersion: v1
kind: Service
metadata:
  name: hotels-vm
  namespace: travel-agency
  labels:
    app: hotels-vm
spec:
  ports:
    - port: 8000
      name: http
  selector:
    kubevirt.io/domain: hotels-vm