apiVersion: v1
kind: Service
metadata:
  name: insurances-vm
  namespace: travel-agency
  labels:
    app: insurances-vm
spec:
  ports:
    - port: 8000
      name: http
  selector:
    kubevirt.io/domain: insurances-vm