apiVersion: v1
kind: Service
metadata:
  name: mysqldb-vm
  namespace: travel-agency
  labels:
    app: mysqldb-vm
spec:
  ports:
    - port: 3306
      name: tcp
  selector:
    kubevirt.io/domain: mysqldb-vm