apiVersion: v1
kind: Service
metadata:
  name: travels-vm
  namespace: travel-agency
  labels:
    app: travels-vm
spec:
  ports:
    - port: 8000
      name: http
  selector:
    kubevirt.io/domain: travels-vm